### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by dmitriy-saenko** [astorm/magento2-tutorial-proxy-objects#1]
Hey Alan,

Thanks for your tutorials, i enjoy them.
I've tried to enable proxy as you wrote in the article.
The proxy class has been generated.
When i run it i getting segmentation fault, please read bellow:

$ php bin/magento ps:tutorial-proxy
About to Create Service
Constructing FastLoading Object
Constructing SlowLoading Object
Created Service, approximate time to load: 3005.1239 ms

About to say hello with fast object
Hello
Said hello with fast object, approximate time to load: 0.0112 ms

About to say hello with slow object
Segmentation fault: 11

Do you have any guessing why it happens?
Thanks for your reply

**Comment by dmitriy-saenko** [comment]
I've found the problem

this one should be replaced 

< preference for="Pulsestorm\TutorialProxy1\Model\SlowLoading type="Pulsestorm\TutorialProxy1\Model\SlowLoading\Proxy" /> 

```
<type name="Pulsestorm\TutorialProxy1\Model\Example">
    <arguments>
        <argument name="slow" xsi:type="object">Pulsestorm\TutorialProxy1\Model\SlowLoading\Proxy</argument>
    </arguments>
</type>
```

**Comment by astorm** [comment]
@dmitriy-saenko Was this a problem with the tutorial text, or had you mis-transcribed something?  If it's the former, could you let us know which step of the tutorial you were at?
